name = "s4hana-migration-assistant"
compatibility_date = "2024-08-14"

# For standard Docker deployment via GitHub Actions
# The Docker container will run independently

# Environment variables
[vars]
NODE_ENV = "production"
PORT = "8080"

# Uncomment and configure these for production deployment
# DATABASE_URL = "your-production-neon-database-url"
# SESSION_SECRET = "your-production-session-secret"