name = "migration-assistant"
main = "server/index.ts"
compatibility_date = "2025-06-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "migration-assistant-prod"
account_id = "${ACCOUNT_ID}"
main = "worker/index.ts"

[[env.production.d1_databases]]
binding = "DB"
database_name = "migration-assistant-db"
database_id = "${DATABASE_ID}"

[env.production.durable_objects]
bindings = [
	{ name = "BACKEND", class_name = "Backend" }
]

[[env.production.containers]]
class_name = "Backend"
image = "./Dockerfile"

[[env.production.migrations]]
new_sqlite_classes = ["Backend"]
tag = "v1"

[env.production.vars]
NODE_ENV = "production"

[env.production.observability]
enabled = true