name = "s4hana-migration-assistant"
compatibility_date = "2024-08-14"

# Docker deployment configuration
main = "dist/index.js"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# Environment variables
[vars]
NODE_ENV = "production"
PORT = "8080"

# Uncomment and configure these for production
# [vars]
# DATABASE_URL = "your-production-neon-database-url"
# SESSION_SECRET = "your-production-session-secret"

# For development/preview
[env.preview.vars]
NODE_ENV = "development"
PORT = "8080"

# Docker configuration
[docker]
dockerfile = "Dockerfile"