name: Build and Test Docker Container

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Test Docker Container

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t s4hana-migration-assistant .

      - name: Test Docker container
        run: |
          docker run -d --name test-container -p 8080:8080 \
            -e NODE_ENV=test \
            -e SESSION_SECRET=test-secret \
            s4hana-migration-assistant
          sleep 15
          curl -f http://localhost:8080/api/health || exit 1
          docker stop test-container
          docker rm test-container

      - name: Docker deployment ready
        run: |
          echo "✅ Docker container built and tested successfully!"
          echo "🚀 Ready for manual deployment to your preferred platform"
          echo "📋 Available deployment options:"
          echo "   - Cloudflare (when Container Workers are generally available)"
          echo "   - Railway, Render, or other Docker-compatible platforms"
          echo "   - Self-hosted Docker environment"